name: "Translation error 📚"
description: Report an incorrect or missing translation
labels: Translation, New request
assignees: JueK3y-Prv
body:
- type: markdown
  attributes:
    value: |
      Please make sure to [search for existing translation errors](https://github.com/JueK3y/Instagram-automated-commenting/issues?q=is%3Aopen+is%3Aissue+label%3ATranslation) and [check the FAQ](https://github.com/JueK3y/Instagram-automated-commenting/wiki/FAQ) before filing a new one!
 
- type: dropdown
  attributes:
    label: In what language is the translation error?
    options:
      - German
      - English
      - Other language
  validations:
    required: true
 
- type: textarea
  attributes:
    label: Where is the incorrect / missing translation located?
    description: Briefly describe how to find the translation error
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. See missing translation in line '...'
  validations:
    required: true
 
- type: textarea
  attributes:
    label: What is the incorrect / missing translation?
    placeholder: This is ein Feld with german text.
  validations:
    required: true
 
- type: textarea
  attributes:
    label: What translation do you suggest?
    placeholder: This is a field with german text.
  validations:
    required: false